mode: rule
allow-lan: true
unified-delay: true
bind-address: '*'
log-level: silent
ipv6: false
geodata-mode: true
external-controller: 0.0.0.0:9090
external-ui: dashboard/dist
tcp-concurrent: false
interface-name: ""
enable-process: false
geodata-loader: memconservative
inbound-tfo: true
secret: ""
profile:
  store-selected: true
  store-fake-ip: false
# geox-url: {mmdb: "https://cdn.jsdelivr.net/gh/Dreamacro/maxmind-geoip@release/Country.mmdb", geoip: "https://github.com/v2fly/geoip/raw/release/cn.dat", geosite: "https://github.com/taamarin/v2ray-rules-dat/raw/release/geosite.dat"}
# experimental:
  # fingerprint: xxxx # 同 experimental.fingerprints 使用 sha256 指纹，配置协议独立的指纹，将忽略 experimental.fingerprints
dns:
  enable: true
  device: Meta
  ipv6: true
  prefer-h3: false #start DOH to use http/3 first
  default-nameserver:
    - 1.1.1.1
    - 9.9.9.9
  listen: 0.0.0.0:1053
  use-hosts: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter: ['networktest.twilio.com', '+.twilio.com', 'connect.rom.miui.com', '+.msftnsci.com', '+.msftconnecttest.com', '+.gstatic.com', '+.stun.*.*', '+.stun.*.*.*', '+.stun.*.*.*.*', '+.time.*', '+.time.*.*', '+.time.*.*.*', '+.ntp.*', '+.ntp.*.*', '+.ntp.*.*.*']
  nameserver:
    - 172.67.199.34 ## GANTI BUG YG KALIAN GUNAKAN 
    - https://1.1.1.1/dns-query
    - tls://dns.quad9.net
    - quic://dns.adguard.com
#  proxy-server-nameserver:
#    - 172.67.199.34
#  fallback:
#    - https://dns.google/dns-query
#    - https://1.1.1.1/dns-query
#  fallback-filter:
#    geoip: false
#    geoip-code: "ID"
#    geosite:
#      - GFW
#    ipcidr:
#      - 0.0.0.0/32
#    domain: ['+.google.com', '+.facebook.com', '+.youtube.com', '+.githubusercontent.com', '+.googlevideo.com', '+.msftconnecttest.com', '+.msftncsi.com', 'msftconnecttest.com', 'msftncsi.com']
# feature CLASH PREMIUM 
# auto-redir:
#  enable: false
#  auto-route: false
tun:
  enable: false
  stack: system
  dns-hijack:
    - any:53
  auto-route: false
  auto-detect-interface: false
sniffer:
  enable: false
  sniffing: ['tls', 'http']
  force-domain: ['+']
  skip-domain: ['+.google.com']
  port-whitelist: ['443', '80']
hosts:
  'cacerts.digicert.com': 172.67.199.34
tproxy-port: 9898
proxy-groups:
- name: 📥
  type: select
  use:
    - 7six Provider 1
  - name: proxy
    type: select
    proxies:
      - 📥
      - Auto
      - Load balance
  - name: Auto 
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
       - 7six Provider 1
  - name: Load balance
    type: load-balance
    strategy: consistent-hashing
    disable-udp: false
    proxies:
        - 7six Provider 1
    url: http://www.gstatic.com/generate_204
    interval: 300
#  - name: GAMEMAX
#    type: select
#    proxies:
#      - DIRECT
#    url: 'http://www.gstatic.com/generate_204'
#    interval: 100
  - name: SOSMED
    type: select
    proxies:
      - Auto
    url: 'http://www.gstatic.com/generate_204'
    interval: 100
  - name: STREAMING
    type: select
    proxies:
      - Load balance
    url: 'http://www.gstatic.com/generate_204'
    interval: 100
  - name: "Ads"
    type: select
    proxies:
      - REJECT
      - DIRECT
proxy-providers:
  7six Provider 1:
    type: http
    path: ./7six.yaml
    url: https://raw.githubusercontent.com/7siix/7sixx_CMFA_Magisk/main/7six._magisk_provider.yaml
    interval: 3600
    health-check:
      enable: true
      interval: 300
      lazy: true
      url: http://www.gstatic.com/generate_204
rule-providers:
 # Gaming:
 #   type: http
 #   behavior: classical
 #   path: "./confs/ruleset/Gamemax.yaml"
 #   url: https://raw.githubusercontent.com/7siix/punya76/main/ruleGamemax.yaml
 #   interval: 86400
  Sosmed:
    type: http
    behavior: domain
    path: "./confs/ruleset/Sosmed.yaml"
    url: https://raw.githubusercontent.com/7siix/punya76/main/Rule-Sosmed.yaml
    interval: 86400
  Streaming:
    type: http
    behavior: classical
    path: "./confs/ruleset/Streaming.yaml"
    url: https://raw.githubusercontent.com/7siix/punya76/main/Streaming.yaml
    interval: 86400
  ADs:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/reject.txt"
    path: ./confs/ruleset/all-ads.yaml
    interval: 86400 
rules:
  - PROCESS-NAME,com.whatsapp,Auto
  - PROCESS-NAME,com.android.chrome,Auto
#  - RULE-SET,Gaming,GAMEMAX
  - RULE-SET,Sosmed,SOSMED
  - RULE-SET,Streaming,STREAMING
  - RULE-SET,ADs,Ads
  - MATCH,7six
